### ISSUE TITLE
Feedback from Zalando Checklist

### ISSUE THREAD

**Issue by Friedrich-Mueller** [privML/privacy-evaluator#202]
- [x] Put the Zalando feedback doc contents in here
- [x] Add checkboxes to every line/point to make sure that not a single thing stays unaddressed

Feedback document:
https://docs.google.com/document/d/1DcD8nM3w2c3aC88JVU-rq4uuYW_v2LGoKdv_PPL10OE/edit#
#### General
- [x] Unclear why the test set was passed to attack. #190 
- [X] The meaning of attack_model_accuracy reported was not very clear to the users. 
- [x] Unclear how the attack model accuracy can be improved. No recommendations provided. #195 
- [x] Explanation: ‘Lowest possible accuracy is 50%.’ “Average?” #192 
#### Slicing: 
- [x] “What is a slice? What is the size of a slice? Why 13?” #193 
- [X] “classification_correctness definition? Of the attack?” 
- [x] “How to read the output?” #193
#### Attack analysis: 
- [x] “What does accuracy mean here?” #193 
- [x] “Why are x_train and x_test concatenated?” #196 
#### Risk scores: 
- [x] “What do they mean? Should they be high or low?” #197 
- [x] “How to interpret the histogram? Number of points in class above best threshold? Top 50 points per label?” #198 
- [x] “Can I get privacy risk scores for individual data points?” #198 
- [x] “I want the distribution of privacy risk scores per class.” #199 
- [x] Users unsure about whether the attack was pointwise or not. #198 
- [x] Users were not able to report results to tester not being confident about interpretation. Not unexpected. #201 
“Very usable. Super well explained”

**Comment by Friedrich-Mueller** [comment]
I have no preference, but it might be easiest if we just put a comment/strike-through in a copy of this document, which for one, allows to mark something as done, and additionally, allows for someone to leave a comment on an individual line or piece of feedback.

It would just save a lot of work in regards to converting docx to markdown.
